version: '3.3'
services:
  db:
    image: runcor3/spring-boot-admin-mysql:1.0
    restart: always
    container_name: db
    ports:
      - '3306:3306'
 
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: App_Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - db
    container_name: spring-boot-admin

volumes:
  db-data:
